import sys, os
from http.client import BAD_REQUEST, OK
from typing import Tuple

from src.core.exceptions import (
    RepositoryException, UseCaseRuleException, UseCaseBusinessException, ValidatorException
)
from src.core.messages import INCONSISTENCY_MESSAGE_FOUND


class BaseController:
    business_class = None
    
    def __init__(self, repository: object):
        self.business = self.business_class(repository)

    def _send_email_error(self, exception: Exception):
        exc_type, exc_value, exc_traceback = sys.exc_info()
        trace = exception.__traceback__

        # TODO - Kayo: simulate sending email.
        print(f"""
            *****************************************************
            WARNING: Exception generated by the system.


            type               : {exc_type.__name__}
            message            : {exc_value.message}
            error              : {exc_value.error}
            traces             : 
        """)

        while trace is not None:
            print(f"""
                -------------------------------------------------  
                ---> path and file name : {trace.tb_frame.f_code.co_filename}
                ---> line code          : {trace.tb_lineno}
                ---> method name        : {trace.tb_frame.f_code.co_name}
                -------------------------------------------------
            """)

            trace = trace.tb_next

        print(f"""
            *****************************************************
        """)

    def _to_try(self, callback):
        try:
            result = callback()

        except RepositoryException as err:
            self._send_email_error(err)
            
            # TODO - Kayo: display nice message and send error message to technical control.
            return {'message': INCONSISTENCY_MESSAGE_FOUND % err.message}, BAD_REQUEST.value

        except ValidatorException as err:
            self._send_email_error(err)

            # TODO - Kayo: display nice message and send error message to technical control.
            return {'message': INCONSISTENCY_MESSAGE_FOUND % err.message}, BAD_REQUEST.value
        
        except UseCaseRuleException as err:
            self._send_email_error(err)

            # TODO - Kayo: display nice message and send error message to technical control.
            return {'message': INCONSISTENCY_MESSAGE_FOUND % err.message}, BAD_REQUEST.value

        except UseCaseBusinessException as err:
            self._send_email_error(err)

            # TODO - Kayo: display nice message and send error message to technical control.
            return {'message': INCONSISTENCY_MESSAGE_FOUND % err.message}, BAD_REQUEST.value
        
        return result, OK.value

    def get(self, pk: int) -> Tuple[dict, int]:
        def do_get():
            return self.business.get(pk)
        
        return self._to_try(do_get)

    def list(self, page: int, page_size: int) -> Tuple[list, int]:
        def do_list():
            return self.business.get_availables(page, page_size)
        
        return self._to_try(do_list)
